[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python src/web/app.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "web"
serviceType = "web"
internal_port = 5000

[[services.ports]]
port = 5000
type = "HTTP"
